name: apod-data-extractor

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  apod-data-extractor:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run start
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name 'automated_prajwal'
            git config --global user.email 'mail2prajwal12@gmail.com'
            git add .
            git commit -m "Automated data update"
            git push
          else
            echo "no changes";
          fi