name: apod-bulk-extractor

on:
  workflow_dispatch:
    inputs:
      startdate:
        description: 'Please enter start date for data extraction, YYYY-MM-DD'
        required: true
        default: '2022-01-01'
      enddate:
        description: 'Please enter end date for data extraction, YYYY-MM-DD'
        required: true
        default: '2022-01-05'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: run shell script
        run: |
          #!/bin/bash

          pwd

          startdate='${{ github.event.inputs.startdate }}'
          enddate='${{ github.event.inputs.enddate }}'
          thedate=$( date -d "$startdate" +%Y-%m-%d )
          
          while [ "$thedate" != "$enddate" ]; do
              commitdate=$( date -d "$thedate" +%Y-%M-%D )
              printf 'The date is "%s"\n' "$thedate"
              printf 'Commit date is "%s"\n' "$commitdate"

              response=$(curl --location --request GET 'https://apod.ellanan.com/api?date='$thedate)
              echo "$response" > extracted_data/"$thedate.json"
              
              git config --global user.name 'automated_prajwal'
              git config --global user.email 'mail2prajwal12@gmail.com'
              git add .
              git commit --date="$commitdate 09:30:00" -m "Automated data update $thedate"
              #git push

              thedate=$( date -d "$thedate + 1 days" +%Y-%m-%d ) # increment by one day
          done
          
          cd extracted_data && ls -lrta
