name: apod-data-extractor-python

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Fetch new APOD data and commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run python script
        run: |
          python src/basic.py
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name 'automated_prajwal'
            git config --global user.email 'mail2prajwal12@gmail.com'
            git add .
            git commit -m "Automated data update - Python script - `date +'%Y-%m-%d %H:%M:%S'`"
            git push
          else
            echo "no changes";
          fi
  slack-notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_MESSAGE: 'APOD data fetch completed :rocket:'
        SLACK_TITLE: APOD action
        SLACK_COLOR: ${{ job.status }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
