name: Deploy Docker On EC2

on:
  workflow_run:
    workflows: ["ci-cd-main"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into EC2 Instance and Stop Existing Containers
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST_IP }} << EOF
            sudo docker stop apod-api || true
            sudo docker rm apod-api || true
            sudo docker rmi apod-api || true
          EOF

      - name: SSH into EC2 Instance and Run Docker Containers
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST_IP }} << EOF
            sudo docker pull mail2prajwal12/apod-api:latest
            sudo docker run -d --name apod-api -p 8888:8888 mail2prajwal12/apod-api:latest
          EOF
