name: Run Python Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run pip install requests
        run: |
          python3 -m pip install requests
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: run python shell script
        run: |
          pip show

          import os
          import requests

          print("Directory contents:")
          for f in os.listdir():
              print(f)
          
          baseURL = 'https://apod.ellanan.com/api'
          response = requests.get(baseURL)
          print('---------------------------------------------------------------------------------------------')
          print(response.status_code)
          print('---------------------------------------------------------------------------------------------')
          print(response.json())